# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.DateField(null=True),
        ),
    ]
